
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: oms_ror_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  <<: *default
  database: oms_ror_test

production:
  <<: *default
  database: oms_ror_production
  username: oms_ror
  password: <%= ENV["OMS_ROR_DATABASE_PASSWORD"] %>
